export { watchAccuracyTracker } from './tool/watch-accuracy-tracker/entry';
export type { WatchAccuracyTrackerUI, WatchAccuracyTrackerLocaleContent } from './tool/watch-accuracy-tracker/entry';
export { wristPresenceCalculator } from './tool/wrist-presence-calculator/entry';
export type { WristPresenceCalculatorUI, WristPresenceCalculatorLocaleContent } from './tool/wrist-presence-calculator/entry';
export { demagnetizingTimer } from './tool/demagnetizing-timer/entry';
export type { DemagnetizingTimerUI, DemagnetizingTimerLocaleContent } from './tool/demagnetizing-timer/entry';
export { watchSavingsPlanner } from './tool/watch-savings-planner/entry';
export type { WatchSavingsPlannerUI, WatchSavingsPlannerLocaleContent } from './tool/watch-savings-planner/entry';
export { crownReferenceGuide } from './tool/crown-reference-guide/entry';
export type { CrownReferenceGuideUI, CrownReferenceGuideLocaleContent } from './tool/crown-reference-guide/entry';
export { powerReserveEstimator } from './tool/power-reserve-estimator/entry';
export type { PowerReserveEstimatorUI, PowerReserveEstimatorLocaleContent } from './tool/power-reserve-estimator/entry';
export { beatRateConverter } from './tool/beat-rate-converter/entry';
export type { BeatRateConverterUI, BeatRateConverterLocaleContent } from './tool/beat-rate-converter/entry';
export { waterResistanceConverter } from './tool/water-resistance-converter/entry';
export type { WaterResistanceConverterUI, WaterResistanceConverterLocaleContent } from './tool/water-resistance-converter/entry';
export { strapTaperCalculator } from './tool/strap-taper-calculator/entry';
export type { StrapTaperCalculatorUI, StrapTaperCalculatorLocaleContent } from './tool/strap-taper-calculator/entry';
export { watchSizeComparator } from './tool/watch-size-comparator/entry';
export type { WatchSizeComparatorUI, WatchSizeComparatorLocaleContent } from './tool/watch-size-comparator/entry';
export { lumeColorSimulator } from './tool/lume-color-simulator/entry';
export type { LumeColorSimulatorUI, LumeColorSimulatorLocaleContent } from './tool/lume-color-simulator/entry';
export { moonPhaseVisualizer } from './tool/moon-phase-visualizer/entry';
export type { MoonPhaseVisualizerUI, MoonPhaseVisualizerLocaleContent } from './tool/moon-phase-visualizer/entry';
export { tachymeterCalculator } from './tool/tachymeter-calculator/entry';
export type { TachymeterCalculatorUI, TachymeterCalculatorLocaleContent } from './tool/tachymeter-calculator/entry';
export { serviceIntervalTracker } from './tool/service-interval-tracker/entry';
export type { ServiceIntervalTrackerUI, ServiceIntervalTrackerLocaleContent } from './tool/service-interval-tracker/entry';
export { strapLengthCalculator } from './tool/strap-length-calculator/entry';
export type { StrapLengthCalculatorUI, StrapLengthCalculatorLocaleContent } from './tool/strap-length-calculator/entry';
export { telemeterCalculator } from './tool/telemeter-calculator/entry';
export type { TelemeterCalculatorUI, TelemeterCalculatorLocaleContent } from './tool/telemeter-calculator/entry';
export { siderealTimeTracker } from './tool/sidereal-time-tracker/entry';
export type { SiderealTimeTrackerUI, SiderealTimeTrackerLocaleContent } from './tool/sidereal-time-tracker/entry';
export { gearTrainExplorer } from './tool/gear-train-explorer/entry';
export type { GearTrainExplorerUI, GearTrainExplorerLocaleContent } from './tool/gear-train-explorer/entry';
export { perpetualCalendar } from './tool/perpetual-calendar/entry';
export type { PerpetualCalendarUI, PerpetualCalendarLocaleContent } from './tool/perpetual-calendar/entry';
export { tourbillonVisualizer } from './tool/tourbillon-visualizer/entry';
export type { TourbillonUI, TourbillonLocaleContent } from './tool/tourbillon-visualizer/entry';
export { gmtWorldTimer } from './tool/gmt-world-timer/entry';
export type { GMTWorldTimerUI, GMTWorldTimerLocaleContent } from './tool/gmt-world-timer/entry';
export { quartzBatteryHealth } from './tool/quartz-battery-health/entry';
export type { QuartzBatteryHealthUI, QuartzBatteryHealthLocaleContent } from './tool/quartz-battery-health/entry';
export { mainspringFinder } from './tool/mainspring-finder/entry';
export type { MainspringFinderUI, MainspringFinderLocaleContent } from './tool/mainspring-finder/entry';
export { chronoCategory } from './category';

import { watchAccuracyTracker } from './tool/watch-accuracy-tracker/entry';
import { wristPresenceCalculator } from './tool/wrist-presence-calculator/entry';
import { demagnetizingTimer } from './tool/demagnetizing-timer/entry';
import { watchSavingsPlanner } from './tool/watch-savings-planner/entry';
import { crownReferenceGuide } from './tool/crown-reference-guide/entry';
import { powerReserveEstimator } from './tool/power-reserve-estimator/entry';
import { beatRateConverter } from './tool/beat-rate-converter/entry';
import { waterResistanceConverter } from './tool/water-resistance-converter/entry';
import { strapTaperCalculator } from './tool/strap-taper-calculator/entry';
import { watchSizeComparator } from './tool/watch-size-comparator/entry';
import { lumeColorSimulator } from './tool/lume-color-simulator/entry';
import { moonPhaseVisualizer } from './tool/moon-phase-visualizer/entry';
import { tachymeterCalculator } from './tool/tachymeter-calculator/entry';
import { serviceIntervalTracker } from './tool/service-interval-tracker/entry';
import { strapLengthCalculator } from './tool/strap-length-calculator/entry';
import { telemeterCalculator } from './tool/telemeter-calculator/entry';
import { siderealTimeTracker } from './tool/sidereal-time-tracker/entry';
import { gearTrainExplorer } from './tool/gear-train-explorer/entry';
import { perpetualCalendar } from './tool/perpetual-calendar/entry';
import { tourbillonVisualizer } from './tool/tourbillon-visualizer/entry';
import { gmtWorldTimer } from './tool/gmt-world-timer/entry';
import { quartzBatteryHealth } from './tool/quartz-battery-health/entry';
import { mainspringFinder } from './tool/mainspring-finder/entry';

export const ALL_ENTRIES = [watchAccuracyTracker, wristPresenceCalculator, demagnetizingTimer, watchSavingsPlanner, crownReferenceGuide, powerReserveEstimator, beatRateConverter, waterResistanceConverter, strapTaperCalculator, watchSizeComparator, lumeColorSimulator, moonPhaseVisualizer, tachymeterCalculator, serviceIntervalTracker, strapLengthCalculator, telemeterCalculator, siderealTimeTracker, gearTrainExplorer, perpetualCalendar, tourbillonVisualizer, gmtWorldTimer, quartzBatteryHealth, mainspringFinder];

